
[program:Kahungunu]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Kahungunu -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Kahungunu'
# http://icecast.iwi.radio:8000/Kahungunu


[program:KiaOra]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/KiaOra -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/KiaOra'
# http://icecast.iwi.radio:8000/KiaOra


[program:MFM]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/MFM -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/MFM'
# http://icecast.iwi.radio:8000/MFM


[program:NgatiHine]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/NgatiHine -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/NgatiHine'
# http://icecast.iwi.radio:8000/NgatiHine


[program:Raukawa]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Raukawa -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Raukawa'
# http://icecast.iwi.radio:8000/Raukawa


[program:Atiawa]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Atiawa -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Atiawa'
# http://icecast.iwi.radio:8000/Atiawa


[program:TeUpoko]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/TeUpoko -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/TeUpoko'
# http://icecast.iwi.radio:8000/TeUpoko


[program:Tumeke]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Tumeke -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Tumeke'
# http://icecast.iwi.radio:8000/Tumeke


[program:Tuwharetoa]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Tuwharetoa -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Tuwharetoa'
# http://icecast.iwi.radio:8000/Tuwharetoa


[program:Waatea]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://icast1.streamcom.net/Waatea -c:a aac -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/Waatea'
# http://icecast.iwi.radio:8000/Waatea


[program:NgaIwi]
autorestart=true
autostart=true
startretries=99999
command=/bin/ffmpeg -re -i http://apple.irirangi.net:8000/D_Nga_Iwi.aac -c:a aac -profile:a aac_he -b:a 64k -nostdin -loglevel warning -content_type 'audio/aac' -vn -f adts 'icecast://source:Wh4k4ruruh4u!1991@icecast.iwi.radio:8000/NgaIwi'
# http://icecast.iwi.radio:8000/Waatea
