---

- name: Get instance info
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
    filters:
      tag:project_env: "{{ project_name }}_{{ env_type }}"
  register: ec2_facts


- name: Set ec2_server ec2_facts
  ansible.builtin.set_fact:
    ec2_server: "{{ ec2_facts.instances.0 }}"


- name: Ensure ec2 is running
  delegate_to: localhost
  amazon.aws.ec2_instance:
    instance_ids: "{{ ec2_server.instance_id }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
    wait_timeout: 500

- name: Wait for SSH to come up
  ansible.builtin.wait_for:
    host: "{{ ec2_server.public_dns_name }}"
    port: 22
    delay: 120
    timeout: 320
    state: started
  when: ec2_server.state.name != 'running'

- name: Get ec2 instance info
  amazon.aws.ec2_instance_info:
    region: "{{ aws_region }}"
    filters:
      tag:project_env: "{{ project_name }}_{{ env_type }}"
  register: ec2_facts

- name: Set ec2_server var
  ansible.builtin.set_fact:
    ec2_server: "{{ ec2_facts.instances[0] }}"

- name: Write the new ec2 instance host key to known hosts
  connection: local
  ansible.builtin.shell: "ssh-keyscan -H {{ ec2_server.public_ip_address }} >> ~/.ssh/known_hosts"

- name: refresh_inventory
  ansible.builtin.meta: refresh_inventory
