---
ec2_key_pair : libretime
project_name: icecast
ssl_dest_dir: /etc/ssl
aws_region: ap-southeast-2
timezone: Pacific/Auckland

domain_name: tehiku.radio
application_subdomain: listen
network_subdomain: icecast
host_name: listen.tehiku.radio
