---
- ansible.builtin.include_tasks: create_target_group.yml
- ansible.builtin.include_tasks: create_load_balancer_security_group.yml
- ansible.builtin.include_tasks: create_load_balancer.yml
- ansible.builtin.include_tasks: attach_domain_to_elb.yml
