# Tasks for creating security groups

- name: Create Web security group
  delegate_to: localhost
  amazon.aws.ec2_security_group:
    name: "{{ security_group_name }}"
    description: "Security group for {{ project_name }} {{ env_type }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8000
        to_port: 8000
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  register: ec2_group
  tags:
    sg_config

# Tasks for launching instances
- name: Launch webserver instance
  delegate_to: localhost
  amazon.aws.ec2_instance:
    region: "{{ aws_region }}"
    key_name: "{{ ec2_key_pair }}"
    security_group: "{{ security_group_name }}"
    instance_type: "{{ webserver_instance_type }}"
    image_id: "{{ webserver_ami }}"
    wait: true
    exact_count: 1
    name: "{{ server_name }}"
    purge_tags: true
    tags:
      project_env_server_type: "{{ project_name_tag }}_{{ env_type }}"
      Name: "{{ server_name }}"
      env_type: "{{ env_type }}"
      server_type: "web"
      app: "{{ project_name }}"
      project_env: "{{ project_name }}_{{ env_type }}"
    filters:
      tag:project_env_server_type: "{{ project_name_tag }}_{{ env_type }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_type: gp2
          volume_size: 250
          delete_on_termination: true
    termination_protection: true
  register: ec2_webserver


- name: Tag the ebs
  amazon.aws.ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ ec2_webserver.instances.0.block_device_mappings.0.ebs.volume_id }}"
    state: present
    tags:
      Name: "{{ server_name }}"
      env_type: "{{ env_type }}"
      server_type: "web"
      app: "{{ env_type }}"
      env_server_type: "{{ env_type }}_{{ server_type }}"
      project: "{{ project_name }}"


- name: Debug
  ansible.builtin.debug:
    var: ec2_webserver.tagged_instances[0].instance_id
